name: Deploy to IPFS via Storacha
# Triggering from correct branch
on:
  push:
    branches:
      - storacha

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install w3cli
        run: npm install -g @web3-storage/w3cli

      - name: Upload to Storacha
        run: |
            echo "${{ z6MkvRhStNQ9uFmsKvdzHCxEAgkVhHdwwULG8S8drAgVQu2i }}" > private.key
           - name: Upload to Storacha
  run: |
    echo "${{ secrets.STORACHA_AGENT_DELEGATION }}" | base64 -d > delegation.json
    w3 space use diamond-grey-canary
    w3 upload --recursive ./assets
              w3 space use did:key:z6MkvRhStNQ9uFmsKvdzHCxEAgkVhHdwwULG8S8drAgVQu2i
              w3 upload blockchains/ethereum/assets/0x018bbb44Bb0B3D67fe85B07c083E5cf7